### ISSUE TITLE
Mobile menu

### ISSUE THREAD

**Issue by ian-crowther** [Hederis/hederis.github.io#12]
https://www.dropbox.com/s/bzjornjfcv148r1/Screenshot%202018-09-30%2013.35.55.png?dl=0

Currently no indication that there's a menu to click open. 

Menu maintains the appearance of the nav on desktop, which doesn't seem optimal.

@nelliemckesson we might need two separate nav elements - one for desktop/landscape tablet and one for portrait tablet/phone.

**Comment by nelliemckesson** [comment]
This appears to be fixed in the v2-eric branch:

![screen shot 2018-10-09 at 2 07 06 pm](https://user-images.githubusercontent.com/812739/46698746-b8dc1c80-cbcc-11e8-89ef-27a1df69ebbd.png)

![screen shot 2018-10-09 at 2 07 16 pm](https://user-images.githubusercontent.com/812739/46698752-bbd70d00-cbcc-11e8-96b4-c4713a9b5a2a.png)
